language: cpp
branches: master

before_script:
  - mkdir -p build
  - cd build
  - rm -rf *
  - cmake ..

script:
  - make

after_script:
  - cd ..
  - git add .
  - git commit -m "travis auto build"
  - git push